### ISSUE TITLE
Lamp does not responds to commands

### ISSUE THREAD

**Issue by mvaneck83** [denniedegroot/com.luke.roberts#1]
Ey morning,
I have the Luke Roberts lamp. I must say most of the time it works perfect. 

A few times (once or twice a week) i have seen some strange issues. 

- lamp is on and spontaneously the lamp switch to an scene. I can adjust the scene, but in a split second it toggles back to the other scene. Only after rebooting homey (restarting app doesn't solve the problem) will kill the problem

- When I control the luke Roberts lamp manual with the light switch. The tile in the homey app doesn't update with the right status. So lamp in switched on, but in homey it is still off.

Thanks for your time,
Martijn

**Comment by denniedegroot** [comment]
Hi Martijn,

The current problem is that the lamp status isn't synced with Homey because I can't read the lamp information. This is due to missing some bluetooth control in the Homey core (https://github.com/athombv/homey-apps-sdk-issues/issues/81).
As a result of this the light sometimes goes in a 'weird' state because we cannot verify if a message is really received and accepted by the lamp.
